### ISSUE TITLE
No differentiation is made between different potion types.

### ISSUE THREAD

**Issue by TheoRetisch1** [Pugabyte/AutomaticInventory#1]
All potion types are sort into the same chest, there is no differentiation between them. Hopefully you are able to track down the metadata of potions, so different potions are not handled as the same item anymore. I really appreciate that you created this fork, keep it up 👍 

PaperSpigiot: 1.12.2 #1384

**Comment by TheoRetisch1** [comment]
Do you think that you are able to fix this annoying problem? :)

**Comment by Pugabyte** [comment]
I apologize, I am extremely busy with my job and my server. I will get to this eventually
