### ISSUE TITLE
Support for shulker boxes doesn't include the depositall-command

### ISSUE THREAD

**Issue by TheoRetisch1** [Pugabyte/AutomaticInventory#2]
It was a very cool idea to add support for shulker boxes. Unfortunatly the shulker-box support just works for the QuickDeposit-Feature (sneak+leftklick) and not for the /depositall-command. Obviously the depositall-command is the key feature of this plugin and the most used one. I appreciate any help you can provide.

**Comment by Pugabyte** [comment]
I believe this issue is fixed via [bd908ec](https://github.com/Pugabyte/AutomaticInventory/commit/bd908ec3ed33b3f88f26d252afaed52758d6dee4)
